import json
from pathlib import Path

MAPPINGS_DIR = Path(__file__).parent.parent.parent / "models" / "expression_mappings"

GLOBAL_EXPRESSIONS = [
    "neutral",
    "happy",
    "sad",
    "angry",
    "surprised",
    "excited",
    "embarrassed",
    "thinking",
    "blush",
    "smirk",
    "scared",
    "disgusted",
]

# In-memory cache for expression mappings
_mapping_cache: dict[str, dict[str, str]] = {}


def ensure_mappings_dir():
    MAPPINGS_DIR.mkdir(parents=True, exist_ok=True)


def get_expression_mapping(model_id: str) -> dict[str, str]:
    """Load expression mapping for a model (cached)."""
    if model_id in _mapping_cache:
        return _mapping_cache[model_id]

    ensure_mappings_dir()
    path = MAPPINGS_DIR / f"{model_id}.json"
    if path.exists():
        try:
            mapping = json.loads(path.read_text(encoding="utf-8"))
            _mapping_cache[model_id] = mapping
            return mapping
        except (json.JSONDecodeError, ValueError):
            pass

    _mapping_cache[model_id] = {}
    return {}


def save_expression_mapping(model_id: str, mapping: dict[str, str]):
    """Save expression mapping for a model (updates cache)."""
    ensure_mappings_dir()
    path = MAPPINGS_DIR / f"{model_id}.json"
    path.write_text(json.dumps(mapping, indent=2, ensure_ascii=False), encoding="utf-8")
    _mapping_cache[model_id] = mapping


def _get_model_mapping_json(model_id: str) -> dict[str, str]:
    """Fall back to the model's own mapping.json (auto-generated by character.py).
    Converts {emotions: {happy: {expression: "F05"}}} to flat {happy: "F05"} format."""
    from backend.services.character import MODELS_DIR
    import json as _json
    path = MODELS_DIR / model_id / "mapping.json"
    if not path.exists():
        return {}
    try:
        data = _json.loads(path.read_text(encoding="utf-8"))
        emotions = data.get("emotions", {})
        return {k: v.get("expression", "") for k, v in emotions.items() if v.get("expression")}
    except (_json.JSONDecodeError, ValueError, AttributeError):
        return {}


def resolve_expression(model_id: str, global_name: str) -> str:
    """Resolve a global expression name to the actual model expression ID (cached)."""
    # Check expression_mappings/ first (user-saved)
    mapping = get_expression_mapping(model_id)
    if global_name in mapping and mapping[global_name]:
        return mapping[global_name]

    # Fall back to model's own mapping.json (auto-generated)
    fallback = _get_model_mapping_json(model_id)
    if global_name in fallback and fallback[global_name]:
        return fallback[global_name]

    return global_name


def get_model_raw_expressions(model_id: str) -> list[str]:
    """Get the raw expression names from a model's files (for the mapping UI)."""
    from backend.services.character import _find_model3_json, MODELS_DIR, VRM_MODELS_DIR, _detect_model_type

    model_type = _detect_model_type(model_id)

    if model_type == "live2d":
        model_dir = MODELS_DIR / model_id
        model3_path = _find_model3_json(model_dir)
        if not model3_path:
            return []
        try:
            data = json.loads(model3_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, ValueError):
            return []
        exprs = data.get("FileReferences", {}).get("Expressions", [])
        return [e.get("Name", "") for e in exprs if e.get("Name")]

    if model_type == "vrm":
        return ["happy", "angry", "sad", "relaxed", "surprised", "neutral",
                "aa", "ih", "ou", "ee", "oh", "blink"]

    return []
